import { INTEGRATION_BRAND_ASSETS } from "./assets";
import type { IntegrationProviderCatalog } from "./types";

export const INTEGRATION_PROVIDER_CATALOG = {
  whatsapp: {
    title: "WhatsApp",
    description:
      "Conecte números, gerencie permissões, etiquetas e sincronizações.",
    defaultDetail: "Conexões do WhatsApp",
    category: "customer-engagement",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: [
      "connection-management",
      "session-management",
      "lead-ingestion",
      "messaging",
    ],
    featureFlag: null,
    requiredModule: "whatsapp",
    requiredPermission: "whatsapp_view",
    requiresAdmin: false,
    management: { kind: "route", href: "/settings/integrations/whatsapp" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.whatsapp,
      alt: "WhatsApp",
      fallback: "W",
      fallbackClassName: "bg-[#25d366] text-white",
    },
  },
  ai: {
    title: "IA de atendimento",
    description:
      "Atenda, qualifique e direcione leads no WhatsApp com contexto do CRM.",
    defaultDetail: "WhatsApp e CRM",
    category: "customer-engagement",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["ai-assistance", "automation", "messaging"],
    featureFlag: null,
    requiredModule: "ai_agent",
    requiredPermission: "settings_ai",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: { kind: "system", name: "sparkles", label: "IA de atendimento" },
  },
  meta: {
    title: "Meta",
    description: "Receba leads de formulários do Facebook e Instagram no CRM.",
    defaultDetail: "Páginas Meta",
    category: "customer-engagement",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: [
      "connection-management",
      "form-management",
      "lead-ingestion",
      "messaging",
      "marketing-sync",
      "social-sync",
    ],
    featureFlag: null,
    requiredModule: null,
    requiredPermission: "settings_integrations",
    requiresAdmin: true,
    management: { kind: "route", href: "/settings/integrations/meta" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.meta,
      alt: "Meta",
      fallback: "M",
      fallbackClassName: "bg-[#0866ff] text-white",
    },
  },
  "grupo-olx": {
    title: "Canal Pro",
    description:
      "Gerencie o feed imobiliário e a distribuição para os portais do Grupo OLX.",
    defaultDetail: "Hub dos portais",
    category: "real-estate-portals",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: [
      "connection-management",
      "property-publication",
      "lead-ingestion",
    ],
    featureFlag: null,
    requiredModule: "portals",
    requiredPermission: "settings_integrations",
    requiresAdmin: true,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.canalPro,
      alt: "Canal Pro",
      fallback: "CP",
      fallbackClassName: "bg-[#2155d9] text-white",
    },
  },
  zap: {
    title: "ZAP Imóveis",
    description:
      "Publique imóveis no ZAP por meio da conexão existente com o Canal Pro.",
    defaultDetail: "Via Canal Pro",
    category: "real-estate-portals",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["property-publication", "lead-ingestion"],
    featureFlag: null,
    requiredModule: "portals",
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.zapImoveis,
      alt: "ZAP Imóveis",
      fallback: "ZAP",
      fallbackClassName: "bg-[#ff5a35] text-white",
    },
  },
  "viva-real": {
    title: "Viva Real",
    description:
      "Distribua o catálogo para o Viva Real usando o mesmo feed homologado.",
    defaultDetail: "Via Canal Pro",
    category: "real-estate-portals",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["property-publication", "lead-ingestion"],
    featureFlag: null,
    requiredModule: "portals",
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.vivaReal,
      alt: "Viva Real",
      fallback: "VR",
      fallbackClassName: "bg-[#00a86b] text-white",
    },
  },
  olx: {
    title: "OLX",
    description:
      "Envie imóveis e acompanhe a disponibilidade do canal OLX pelo feed central.",
    defaultDetail: "Via Canal Pro",
    category: "real-estate-portals",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["property-publication", "lead-ingestion"],
    featureFlag: null,
    requiredModule: "portals",
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.olx,
      alt: "OLX",
      fallback: "OLX",
      fallbackClassName: "bg-[#6e0ad6] text-white",
    },
  },
  "chaves-na-mao": {
    title: "Chaves na Mão",
    description:
      "Publique imóveis por XML após a homologação contratual do portal.",
    defaultDetail: "Homologação necessária",
    category: "real-estate-portals",
    availability: "requires-homologation",
    defaultStatus: "unavailable",
    capabilities: ["property-publication"],
    featureFlag: null,
    requiredModule: "portals",
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "system",
      name: "building",
      label: "Chaves na Mão",
    },
  },
  "google-calendar": {
    title: "Google Agenda",
    description: "Sincronize atividades e compromissos com sua agenda.",
    defaultDetail: "Agenda",
    category: "automation-data",
    availability: "feature-flagged",
    defaultStatus: "not-connected",
    capabilities: ["connection-management", "calendar-sync"],
    featureFlag: "ENABLE_GOOGLE_CALENDAR_INTEGRATION",
    requiredModule: null,
    requiredPermission: null,
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.googleCalendar,
      alt: "Google Agenda",
      fallback: "G",
      fallbackClassName: "bg-[#4285f4] text-white",
    },
  },
  webhooks: {
    title: "Webhook",
    description:
      "Receba leads e envie eventos assinados por canais seguros e isolados.",
    defaultDetail: "Entrada e saída",
    category: "automation-data",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: [
      "webhook-ingestion",
      "webhook-delivery",
      "lead-ingestion",
    ],
    featureFlag: null,
    requiredModule: "webhooks",
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: { kind: "system", name: "webhook", label: "Webhook" },
  },
  api: {
    title: "API",
    description:
      "Crie leads por uma API autenticada e encaminhe-os à distribuição do CRM.",
    defaultDetail: "API de leads v1",
    category: "automation-data",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["api-access", "lead-ingestion"],
    featureFlag: null,
    requiredModule: "api",
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: { kind: "system", name: "key", label: "API" },
  },
  chatgpt: {
    title: "ChatGPT",
    description:
      "Conecte recursos generativos da OpenAI aos fluxos autorizados do CRM.",
    defaultDetail: "Em breve",
    category: "roadmap",
    availability: "coming-soon",
    defaultStatus: "unavailable",
    capabilities: ["ai-assistance", "automation"],
    featureFlag: null,
    requiredModule: null,
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "none" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.openAI,
      alt: "ChatGPT",
      fallback: "AI",
      fallbackClassName: "bg-[#111827] text-white",
    },
  },
  manychat: {
    title: "ManyChat",
    description:
      "Integre jornadas de automação e conversas criadas no ManyChat.",
    defaultDetail: "Em breve",
    category: "roadmap",
    availability: "coming-soon",
    defaultStatus: "unavailable",
    capabilities: ["automation", "messaging"],
    featureFlag: null,
    requiredModule: null,
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "none" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.manyChat,
      alt: "ManyChat",
      fallback: "M",
      fallbackClassName: "bg-[#65bc54] text-white",
    },
  },
  "google-tag-manager": {
    title: "Google Tag Manager",
    description:
      "Centralize tags e eventos do site publicado pela imobiliária.",
    defaultDetail: "Site publicado",
    category: "site-measurement",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["site-measurement"],
    featureFlag: null,
    requiredModule: "site",
    requiredPermission: "settings_site",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.googleTagManager,
      alt: "Google Tag Manager",
      fallback: "GTM",
      fallbackClassName: "bg-[#246fdb] text-white",
    },
  },
  "google-analytics": {
    title: "Google Analytics",
    description:
      "Instale o GA4 no site publicado e acompanhe audiência e conversões no Google Analytics.",
    defaultDetail: "Site publicado",
    category: "site-measurement",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["site-measurement"],
    featureFlag: null,
    requiredModule: "site",
    requiredPermission: "settings_site",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.googleAnalytics,
      alt: "Google Analytics",
      fallback: "GA",
      fallbackClassName: "bg-[#e37400] text-white",
    },
  },
  "google-search-console": {
    title: "Google Search Console",
    description:
      "Publique a verificação do site para acompanhar o desempenho no Search Console.",
    defaultDetail: "Verificação do site",
    category: "site-measurement",
    availability: "available",
    defaultStatus: "not-connected",
    capabilities: ["site-measurement"],
    featureFlag: null,
    requiredModule: "site",
    requiredPermission: "settings_site",
    requiresAdmin: false,
    management: { kind: "dialog" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.googleSearchConsole,
      alt: "Google Search Console",
      fallback: "GSC",
      fallbackClassName: "bg-[#458cf5] text-white",
    },
  },
  vista: {
    title: "Vista",
    description: "Sincronize o catálogo imobiliário com a plataforma Vista.",
    defaultDetail: "Em breve",
    category: "real-estate-portals",
    availability: "coming-soon",
    defaultStatus: "unavailable",
    capabilities: [
      "connection-management",
      "property-publication",
      "lead-ingestion",
    ],
    featureFlag: null,
    requiredModule: null,
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "none" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.vista,
      alt: "Vista",
      fallback: "V",
      fallbackClassName: "bg-[#0d6efd] text-white",
    },
  },
  instagram: {
    title: "Instagram",
    description:
      "Conecte mensagens, mídia e sinais do Instagram ao relacionamento.",
    defaultDetail: "Em breve",
    category: "roadmap",
    availability: "coming-soon",
    defaultStatus: "unavailable",
    capabilities: ["connection-management", "messaging", "social-sync"],
    featureFlag: null,
    requiredModule: null,
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "none" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.instagram,
      alt: "Instagram",
      fallback: "IG",
      fallbackClassName: "bg-[#e4405f] text-white",
    },
  },
  claude: {
    title: "Claude",
    description:
      "Disponibilize modelos da Anthropic em automações autorizadas.",
    defaultDetail: "Em breve",
    category: "roadmap",
    availability: "coming-soon",
    defaultStatus: "unavailable",
    capabilities: ["ai-assistance", "automation"],
    featureFlag: null,
    requiredModule: null,
    requiredPermission: "settings_integrations",
    requiresAdmin: false,
    management: { kind: "none" },
    icon: {
      kind: "brand",
      src: INTEGRATION_BRAND_ASSETS.claude,
      alt: "Claude",
      fallback: "C",
      fallbackClassName: "bg-[#191919] text-white",
    },
  },
} as const satisfies IntegrationProviderCatalog;
