create table if not exists private.realtime_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null
    references public.organizations(id) on delete cascade,
  user_id uuid,
  audience_user_id uuid,
  event_type text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint realtime_events_event_type_check
    check (char_length(btrim(event_type)) between 1 and 160),
  constraint realtime_events_data_check
    check (jsonb_typeof(data) = 'object')
);

comment on table private.realtime_events is
  'Backend-only durable cursor log for the Vimob SSE invalidation bus. Rows are retained briefly for reconnect replay and cross-replica fan-out.';

create index if not exists realtime_events_organization_cursor_idx
  on private.realtime_events (organization_id, id);

create index if not exists realtime_events_created_at_brin_idx
  on private.realtime_events using brin (created_at);

alter table private.realtime_events enable row level security;

revoke all on table private.realtime_events
  from public, anon, authenticated, service_role;

revoke all on sequence private.realtime_events_id_seq
  from public, anon, authenticated, service_role;
