insert into public.admin_subscription_plans (
  slug,
  name,
  description,
  price,
  billing_cycle,
  trial_enabled,
  trial_days,
  max_users,
  max_leads,
  max_whatsapp_sessions,
  modules,
  is_active,
  is_public
) values
  (
    'starter-197',
    'Vimob Starter',
    'CRM, agenda, WhatsApp e integracao Meta com 7 dias gratis.',
    197,
    'monthly',
    true,
    7,
    5,
    3000,
    1,
    array['crm', 'agenda', 'whatsapp', 'meta'],
    true,
    true
  ),
  (
    'intermediario-297',
    'Vimob Pro',
    'Tudo do Starter, com controle de imoveis e site publico.',
    297,
    'monthly',
    false,
    null,
    10,
    8000,
    2,
    array['crm', 'agenda', 'whatsapp', 'meta', 'properties', 'site'],
    true,
    true
  ),
  (
    'master-497',
    'Vimob Master',
    'Tudo do Pro, com automacoes e integracoes com portais.',
    497,
    'monthly',
    false,
    null,
    20,
    20000,
    3,
    array['crm', 'agenda', 'whatsapp', 'meta', 'properties', 'site', 'automations', 'webhooks', 'api'],
    true,
    true
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  billing_cycle = excluded.billing_cycle,
  trial_enabled = excluded.trial_enabled,
  trial_days = excluded.trial_days,
  max_users = excluded.max_users,
  max_leads = excluded.max_leads,
  max_whatsapp_sessions = excluded.max_whatsapp_sessions,
  modules = excluded.modules,
  is_active = excluded.is_active,
  is_public = excluded.is_public,
  updated_at = now();
