import {
  Activity,
  BarChart3,
  BellRing,
  Bot,
  Building2,
  Calendar,
  CreditCard,
  DollarSign,
  FileText,
  Globe,
  History,
  Home,
  Kanban,
  LayoutDashboard,
  MapPin,
  Megaphone,
  MessageSquare,
  Plug,
  Receipt,
  Settings,
  Shuffle,
  Tags,
  TrendingUp,
  Trophy,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { NavigationIconKey } from '@/config/navigation'

export const NAVIGATION_ICONS: Record<NavigationIconKey, LucideIcon> = {
  activity: Activity,
  barChart: BarChart3,
  bellRing: BellRing,
  bot: Bot,
  building: Building2,
  calendar: Calendar,
  creditCard: CreditCard,
  dashboard: LayoutDashboard,
  dollarSign: DollarSign,
  fileText: FileText,
  globe: Globe,
  history: History,
  home: Home,
  kanban: Kanban,
  mapPin: MapPin,
  megaphone: Megaphone,
  messageSquare: MessageSquare,
  plug: Plug,
  receipt: Receipt,
  settings: Settings,
  shuffle: Shuffle,
  tags: Tags,
  trendingUp: TrendingUp,
  trophy: Trophy,
  users: Users,
  zap: Zap,
}

export function getNavigationIcon(icon: NavigationIconKey) {
  return NAVIGATION_ICONS[icon]
}
