// Canonical public schema types are generated by the Supabase CLI in one file.
// This stable module keeps application imports independent from the generator
// output location while preventing a second hand-written schema from drifting.
export type {
  CompositeTypes,
  Database,
  Enums,
  Json,
  Tables,
  TablesInsert,
  TablesUpdate,
} from '@/integrations/supabase/types'
